url: https://panayiotiska.github.io
baseurl: /ondology-labs/

# Site settings
title: Ondology Labs
email: iraklis@ondologyenterprises.com
description: "Ondology Labs is a blockchain forensics company that specializes in building custom software solutions for businesses of all sizes."

# Team names, titles and social links
people:
- name: Iraklis Anastasiou
  pic: 1
  position: Co-Founder and CEO
  social:
    - title: LinkedIn
      url: #
    - title: Twitter
      url: #

- name: Panayiotis Kattides
  pic: 2
  position: Co-Founder and CTO
  social:
    - title: LinkedIn
      url: #
    - title: Twitter
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: Twitter
    url: https://twitter.com/OndologyLabs
  - title: LinkedIn
    url: https://www.linkedin.com/company/ondology-labs/

# Postal address (add as many lines as necessary)
address:
  - line: 28 October Ave
  - line: Limassol, Cyprus

# Build settings
markdown: kramdown
permalink: pretty
